version: '{build}'
image: Visual Studio 2019

branches:
  only:
  - master

cache:
  - packages -> ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj
  
configuration: Release

pull_requests:
  do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true

before_build:
  - cmd : dotnet --version
  - cmd : dotnet restore ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --verbosity m
  
build_script:
  - cmd: dotnet build ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --no-restore
  - cmd: dotnet pack ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --no-build -p:NuspecFile=/src/Seq.App.Mailgun.nuspec -p:PackageVersion=1.0.%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: \src\Seq.App.Mailgun\bin\${configuration}\*.nupkg
    name: NuGet

deploy:
    - provider: NuGet
      api_key:
          secure: jAS5nyIwacqXwMQl7CAi76q0+NAH3A3fGdvY8SCY+AfnNwSAooWfj4Bym6MPHdDF
      artifact: NuGet

  