version: '{build}'
image: Visual Studio 2019

branches:
  only:
  - master

cache:
  - packages -> ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj
  
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd : dotnet --version
  - cmd : dotnet restore ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --verbosity m
  
build_script:
  - cmd: dotnet publish ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --no-restore

artifacts:
  - path: \*.nupkg
    name: NuGet
  - path: \src\Seq.App.Mailgun\bin\$(configuration)
    name: Seq.App.Mailgun 
    type: zip
  