version: '{build}'
image: Visual Studio 2019

branches:
  only:
  - development

cache:
  - packages -> ./src/Seq.App.Mailgun.csproj
  
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd : dotnet --version
  - cmd : dotnet restore ./src/Seq.App.Mailgun.sln --verbosity m
  
build_script:
  - cmd: dotnet publish ./src/Seq.App.Mailgun.sln --no-restore

  