version: '{build}'
image: Visual Studio 2019

branches:
  only:
  - master

cache:
  - packages -> ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj
  
configuration: Release

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd : dotnet --version
  - cmd : dotnet restore ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --verbosity m
  
build_script:
  - cmd: dotnet build ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --no-restore
  - cmd: dotnet pack ./src/Seq.App.Mailgun/Seq.App.Mailgun.csproj --no-build -p:PackageVersion=1.0.%build%

artifacts:
  - path: \src\Seq.App.Mailgun\bin\Release\netstandard2.0\*.nupkg
    name: NuGet

  